name: Cypress Tests
on: [push]
jobs:
  cypress-run:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
      - name: Cypress.io
        uses: cypress-io/github-action@v5.6.1
        with:
          record: --record --key f57b0b52-2b43-4e7b-8458-04f60ccbbe43c
          start: npm start 

        
